services:
  network-deploy-service:
    networks:
      -eazybank
  microservice-base-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_PROFILES_ACTIVE: default
  microservice-configserver-config:
    extends:
      service: network-deploy-service
      