spring:
  application:
    name: "configserver"

  profiles:
    active: git
  cloud:
    config:
      server:

        #native:
         # search-locations: "file:///D://Microservice//documents//config"
        git:
          uri: "https://github.com/yogeshsutar63/bank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: "34DFAF32432DFAG234343DGASDFAFF"
server:
  port: 8071
