server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    streams:
      bindings:
        emailsms-in-O:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-O:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            -localhost: 9092
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 10s